name: higgs-zg-ana
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - defaults
dependencies:
  - awkward
  - conda-pack
  - dill
  - enlighten
  - matplotlib
  - numba
  - pandas
  - pip
  - pyaml
  - pyarrow
  - python=3.9
  - rich
  - tqdm
  - uproot
  - vector
  - xrootd
  - pip:
    - correctionlib
    - pydantic
    - pyqt5-sip
    - pyqtchart
    - pyqtwebengine
