executable          = /afs/cern.ch/user/j/jiehan/private/HiggsZGammaAna/final_fit/CMSSW_10_2_13/src/flashggFinalFit/Combine/t2w_jobs/t2w_mu_inclusive.sh
output              = /afs/cern.ch/user/j/jiehan/private/HiggsZGammaAna/final_fit/CMSSW_10_2_13/src/flashggFinalFit/Combine/t2w_jobs/t2w_mu_inclusive.sh.out
error               = /afs/cern.ch/user/j/jiehan/private/HiggsZGammaAna/final_fit/CMSSW_10_2_13/src/flashggFinalFit/Combine/t2w_jobs/t2w_mu_inclusive.sh.err
log                 = /afs/cern.ch/user/j/jiehan/private/HiggsZGammaAna/final_fit/CMSSW_10_2_13/src/flashggFinalFit/Combine/t2w_jobs/t2w_mu_inclusive.sh.log
+JobFlavour         = "workday"
RequestCpus         = 4
queue
