universe   = vanilla
executable = /afs/cern.ch/work/p/pelai/HZgamma/HiggsZGammaAna/hzgml/scripts/run_condor_job.sh
arguments  = "/afs/cern.ch/work/p/pelai/HZgamma/HiggsZGammaAna/hzgml/scripts/runbdt_all.sh $(task)"
log        = /afs/cern.ch/work/p/pelai/HZgamma/HiggsZGammaAna/hzgml/logs/$(task)_condor.log
output     = /afs/cern.ch/work/p/pelai/HZgamma/HiggsZGammaAna/hzgml/logs/$(task)_job.out
error      = /afs/cern.ch/work/p/pelai/HZgamma/HiggsZGammaAna/hzgml/logs/$(task)_job.err
request_cpus   = 1
request_memory = 6 GB
+JobFlavour    = "testmatch"

# espresso=20mins, microcentury=1hr, longlunch=2hr, workday=8hr, tomorrow=1day, testmatch=3 days, nextweek=1 week
# 這行會排四個 job，分別 arguments=1,2,3,4
# ggF
# 1 Hyperparameter v
# 2 Train v
# 3 Apply 
# 4 Score 
# VBF
# 5 Hyperparameter v
# 6 Train v
# 7 Apply v
# 8 Score

queue task in 3